name: Convert OpenAPI3 to Swagger2 in branch

on:
  workflow_dispatch:  # 手動実行

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  convert_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # ブランチ名の末尾を取得（main → main, release/R310 → R310）
      - name: Set short branch name
        run: echo "SHORT_BRANCH_NAME=$(basename ${{ github.ref_name }})" >> $GITHUB_ENV

      # node_modulesのインストールをキャッシュする
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      # 必要な依存関係をインストール
      - name: Install dependencies
        run: npm ci
      
      # `openapi.yaml` の内容を `openapi_303.yaml` にコピー
      - name: Copy openapi.yaml to openapi_303.yaml
        run: |
          cp api/${{ env.SHORT_BRANCH_NAME }}/openapi.yaml api/${{ env.SHORT_BRANCH_NAME }}/openapi_303.yaml

      # `openapi_303.yaml` の1行目を変更
      - name: Update first line in openapi_303.yaml
        run: |
          sed -i '1s/openapi: 3.1.1/openapi: 3.0.3/' api/${{ env.SHORT_BRANCH_NAME }}/openapi_303.yaml
      
      # OpenAPI3仕様ドキュメントをフラット化
      - name: Flatten the OpenAPI3 document
        run: npx openapi-flattener -s api/${{ env.SHORT_BRANCH_NAME }}/openapi_303.yaml -o api/${{ env.SHORT_BRANCH_NAME }}/openapi_flat.yaml
      
      # OpenAPI3からSwagger2へ変換
      - name: Convert OpenAPI3 to Swagger2
        run: npx api-spec-converter --from=openapi_3 --to=swagger_2 --syntax=yaml api/${{ env.SHORT_BRANCH_NAME }}/openapi_flat.yaml > api/${{ env.SHORT_BRANCH_NAME }}/swagger.yaml
      
      # 変換したファイルをコミットしてプッシュ
      - name: Commit and Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin main
          git checkout main
          git pull origin main
          git add api/${{ env.SHORT_BRANCH_NAME }}/openapi_303.yaml
          git add api/${{ env.SHORT_BRANCH_NAME }}/swagger.yaml
          git commit -m "Convert OpenAPI3 to Swagger2 from ${{ github.ref_name }}" || echo "No changes to commit"
          git push origin main

      
